### ISSUE TITLE
Support for SoM / Era 

### ISSUE THREAD

**Issue by lvangh** [braye/wow-profile-copy#1]
Hello, 

Just wondered if you could add suport for classic_era folder structure and allow settings to be copied from there to the Classic Era clusters. 

For example, I was on Shadowstrike SoM, and cloned my characters to the archive Classic Era realm Mankrik. For now I just copied y WTF / SavedVar stuff over which mostly works, but a lot of addons that look for the server name lost their settings.

**Comment by braye** [comment]
Hey, thanks for the feedback! I added support for SoM, etc.. the other day but never cut a release for it.

This should be available with 0.2.6: https://github.com/braye/wow-profile-copy/releases/tag/0.2.6

I've also noticed that *some* addons don't work correctly when copying data between characters. The only one I'm aware of is SexyMap on WoTLK Classic, but if you're experiencing an addon that doesn't work I'd like to know which addons are having problems.
